# Generated by Django 5.2.6 on 2025-09-21 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('math_interest', models.IntegerField()),
                ('science_interest', models.IntegerField()),
                ('literature_interest', models.IntegerField()),
                ('coding_interest', models.IntegerField()),
                ('teamwork', models.IntegerField()),
                ('creativity', models.IntegerField()),
                ('helping_interest', models.IntegerField()),
                ('leadership', models.IntegerField()),
                ('travel_interest', models.IntegerField()),
                ('stable_job_interest', models.IntegerField()),
                ('business_interest', models.IntegerField()),
                ('communication_skills', models.IntegerField()),
                ('career_choice_1', models.CharField(max_length=100)),
                ('career_choice_2', models.CharField(max_length=100)),
                ('career_choice_3', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
